package br.com.warrick.view;

import br.com.warrick.swing.*;

public class Teste_WComponentes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Teste_WComponentes.class.getName());

    /**
     * Creates new form Teste_WComponentes
     */
    public Teste_WComponentes() {
        initComponents();
//        // Array de itens
//        String[] itens = {"Sim", "Não"};
//
//        // Adiciona cada item individualmente
//        for (String item : itens) {
//            wComboBox1.addItem(item);
//            wComboBox2.addItem(item);
//            wComboBox3.addItem(item);
//        }
//
//        // Define que nenhum item deve estar selecionado inicialmente
//       // wComboBox1.setSelectedIndex(-1);
//        wComboBox2.setSelectedIndex(-1);
//        wComboBox3.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        wLabel1 = new br.com.warrick.swing.WLabel();
        wLabel2 = new br.com.warrick.swing.WLabel();
        wLabel3 = new br.com.warrick.swing.WLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wLabel1.setText("Maravilha");
        jPanel2.add(wLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 40));

        wLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wLabel2.setText("Sem Duvidas");
        wLabel2.setLineColor(new java.awt.Color(255, 51, 0));
        jPanel2.add(wLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 120, 40));

        wLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        wLabel3.setText("É IMPOSSIVÉL");
        wLabel3.setLineColor(new java.awt.Color(51, 204, 0));
        jPanel2.add(wLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 120, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Teste_WComponentes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private br.com.warrick.swing.WLabel wLabel1;
    private br.com.warrick.swing.WLabel wLabel2;
    private br.com.warrick.swing.WLabel wLabel3;
    // End of variables declaration//GEN-END:variables
}
